Repository Adventurer13/ExpandedWoodworking, pull requests merged in 2020-11, with the labels that each got.

#38 ReGrowth compatibility
  1.2/Patches/ReGrowth.xml
  1.2/Patches/UniFuel.xml
Labels: enhancement

#40 Add basic compatibility (using a generic wood log) for mods without patches
  1.1/Defs/RecipeDefs/Recipe_Woodworking.xml
  1.1/Defs/ThingDefs/Resources_Wood.xml
  1.1/Patches/UniFuel.xml
  1.1/Patches/zUniLog.xml
  1.2/Defs/RecipeDefs/Recipe_Woodworking.xml
  1.2/Defs/ThingDefs/Resources_Wood.xml
  1.2/Patches/UniFuel.xml
  1.2/Patches/zUniLog.xml
Labels: experimenting, in progress

#39 Royalty patch
  1.2/Patches/A_ExpWoodVanillaRoyalty.xml
Labels: enhancement

#47 Hotfix-1.2.2.2
  1.2/Defs/RecipeDefs/Recipe_Woodworking.xml
  1.2/Patches/A_ExpWoodVanilla.xml
  About/About.xml
  About/Manifest.xml
  About/ModSync.xml
  CHANGELOG.md
Labels: in progress

#48 Hotfix-1.2.2.2 development branch
  1.2/Defs/RecipeDefs/Recipe_Woodworking.xml
  1.2/Patches/A_ExpWoodVanilla.xml
  About/About.xml
  About/Manifest.xml
  About/ModSync.xml
  CHANGELOG.md
Labels: branch update
